### PR TITLE
Feat: Open Webui Pipelines service and integration with Open WebUI frontend

### PR DESCRIPTION
**Pull request by ic4l4s9c**
Initial support for Open WebUI Pipelines and integration with Open WebUI frontend.
Following [wiki](https://github.com/av/harbor/wiki/7.-Adding-A-New-Service):

Added service files:

* `compose.pipelines.yml` — Docker Compose Pipelines service definitions.
* `compose.x.webui.pipelines.yml` — Docker Compose cross-service file for integration with Open WebUI Frontend.

Added configuration files:

* `open-webui/configs/config.pipelines.json` — WebUI Frontend config for connecting to Pipelines API.

Added environment variables override file:
* `pipelines/override.env`

Miscellaneous:
* Service environment variables added to `profiles/default.env`
* Service listed in `README.md`
* Refactored Services/Satellites section in `README.md` for better readability on small screens (please consider my changes, if not let me know, I'll revert it to original formatting)
* Service directory added to `.gitignore`

Please let me know if additions or changes needed.

### CODE REVIEW

**Review by av — APPROVED** [review]
This is awesome, thank you so much and kudos!

I don't mind the README formatting, it looks like the rendered version is identical in either case

**Comment by av** [comment]
Added the docs here:
https://github.com/av/harbor/wiki/2.3.25-Satellite:-Open-WebUI-Pipelines

Thanks again!

**Comment by ic4l4s9c** [comment]
It's probably my mistake for adding section for pipelines default variables not at the end of the `profiles/default.env`, but after [4604e6a](https://github.com/av/harbor/commit/4604e6a4a416727e0e0d37a86e4979ec2b1d8c0f) there is a collision in port mapping between `HARBOR_PIPELINES_HOST_PORT` and `HARBOR_CHATNIO_HOST_PORT`.

**Comment by av** [comment]
Thanks for pointing this out! Resolved in latest `main` by shifting `chatnio` main port to  `34219` (lazy but allows to only update a single wiki entry)

**Pull request merged**
