### PR TITLE
feat: qdrant service

### PR DESCRIPTION
**Pull request by ic4l4s9c**
Initial support for Qdrant.

> Qdrant is a vector similarity search engine and vector database. It provides a production-ready service with a convenient API to store, search, and manage points—vectors with an additional payload Qdrant is tailored to extended filtering support. It makes it useful for all sorts of neural-network or semantic-based matching, faceted search, and other applications.

List of changes:
- Added `compose.qdrant.yml` — Docker Compose Qdrant service definition file.
- Added `qdrant/override.env` — Service environment variables override file.
- Updated `.gitignore`. Excluded `qdrant/storage`.
- Updated `profiles/default.env`. Added variables:
  - `HARBOR_QDRANT_HOST_PORT=34221`
  - `HARBOR_QDRANT_HOST_GRPC_PORT=34231`
  - `HARBOR_QDRANT_VERSION="latest"`
  - `HARBOR_QDRANT_API_KEY="4f81ba2b82664d63cc6af620f0cd1ba46e5894c2f4f148a94ec96c2c70ac5690"`
  - `HARBOR_QDRANT_READ_ONLY_API_KEY="ce103bf74f5de30d192b3b0151eeef95ba50ba99a87cc9c3ccf00ada033290db"`
  - `HARBOR_QDRANT_JWT_RBAC=true`
  - `HARBOR_QDRANT_DISABLE_TELEMETRY=true`
  - `HARBOR_QDRANT_LOG_LEVEL="INFO"`

### CODE REVIEW

**Comment by av** [comment]
Very cool, thank you!

This and other shared vector stores will be useful for extended integration of many other satellites!

**Comment by av** [comment]
Added a small wiki entry here:
https://github.com/av/harbor/wiki/2.3.26-Satellite:-Qdrant

**Comment by ic4l4s9c** [comment]
The URL section of wiki could be more detailed:
> REST API: http://localhost:34221
> Web UI: http://localhost:34221/dashboard
> GRPC API: http://localhost:34222

**Comment by av** [comment]
Sure, updated

**Comment by av** [comment]
This PR (and others) went live in [v0.2.16](https://github.com/av/harbor/releases/tag/v0.2.16)

Thank you again for the contribution! 💪🏻

**Pull request merged**
